### ISSUE TITLE
Dynamically Set Node runtime version (nodejs, nodejs4.3 or nodejs6.10) ?

### ISSUE THREAD

**Issue by jruts** [dwyl/aws-lambda-deploy#33]
Recently AWS launched nodejs 4.3.2 for lambdas. Since this is a public package we want the user to choose the runtime version they prefer, but default it to a specific version (preferably the latest one).

**Comment by nelsonic** [comment]
@jruts I think we should just `default` to `4.3` and if anyone *else* using `dpl` wants to use `v0.10.36` (i.e. "*Legacy*" node) they can *ask* us for it.

**Comment by nelsonic** [comment]
@jruts any objections to me updating the runtime to `nodejs4.3` 
as per: https://aws.amazon.com/blogs/compute/node-js-4-3-2-runtime-now-available-on-lambda/ ?

**Comment by steveoh** [comment]
What about being able to choose the different versions of node?

![image](https://user-images.githubusercontent.com/325813/30949416-67173f50-a3d3-11e7-8b8d-b784b4b7916a.png)

**Comment by nelsonic** [comment]
@steveoh good question! we could _easily_ configure this in the `package.json` "engines" field: https://docs.npmjs.com/files/package.json#engines
and then set it on the lambda accordingly.

**Comment by nelsonic** [comment]
Given that Node.js v12 (LTS) is now the default and should be supported until 2022,
I feel that dynamically setting the Node.js version is no longer needed. 

Closing. (_feel free to re-open if you feel the requirement is still valid_) 👍

**Comment by nelsonic** [comment]
Updating to Node.js v20 which is LTS until 2025: #85
