### ISSUE TITLE
Option to specify the timeout for the lambda

### ISSUE THREAD

**Issue by nikhilaravi** [dwyl/aws-lambda-deploy#41]
At the moment the default is 3 seconds.

**Comment by nelsonic** [comment]
@nikhilaravi what would you like to call these options?
e.g:
+ `lambda_timeout`
+ `lambda_memory`

**Comment by nikhilaravi** [comment]
@nelsonic yes that sounds fine! Is this to add to the package.json?

**Comment by nelsonic** [comment]
yeah, below the `"files_to_deploy"` ...

**Comment by nikhilaravi** [comment]
@nelsonic amazing!

**Comment by nelsonic** [comment]
http://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html

**Comment by nelsonic** [comment]
This is was added in #42 
see: https://github.com/dwyl/aws-lambda-deploy#optional-configuration
