### ISSUE TITLE
tests failing for uploading :-(

### ISSUE THREAD

**Issue by nelsonic** [dwyl/aws-lambda-deploy#56]
Just tried a _fresh_ clone of the repo, `npm install && npm test` and got the following:
![aws-lambda-deploy-tests-failing](https://cloud.githubusercontent.com/assets/194400/19264325/2aaf59d0-8f98-11e6-9373-c229502e5725.png)

Don't have time to _investigate_ right now ... if anyone else does, please go for it!

**Comment by DaMouse404** [comment]
@nelsonic, I looked into this and it was a bug in the aws-sdk. Should be fixed in 2.7.10 😸 .

See: https://github.com/aws/aws-sdk-js/pull/1242

Probably worth setting up something like https://greenkeeper.io/ to monitor when dependencies update?

**Comment by nelsonic** [comment]
@DaMouse404 thanks for confirming that. 👍

**Comment by nelsonic** [comment]
![image](https://cloud.githubusercontent.com/assets/194400/22707540/fd92a17e-ed6a-11e6-88bd-5833fc6a707b.png)

![sad panda](https://media.giphy.com/media/7p3e2WCM0VEnm/giphy.gif)

**Comment by nelsonic** [comment]
![image](https://cloud.githubusercontent.com/assets/194400/22708072/d4d748f0-ed6c-11e6-9753-0dbc3018df70.png)

Tests pass with latest version of `aws-sdk` @2.9.0
